window.QUESTION_BANK = window.QUESTION_BANK || [];

window.QUESTION_BANK.push(
  // LTC (HF/HTN/AF/anticoags)
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Heart failure management", q:"A stable HF patient reports increasing ankle swelling and weight gain over a week. Best nursing action?", choices:["Ignore—common in HF","Assess fluid status, check weight trend, escalate for review/meds adjustment","Advise strenuous exercise immediately","Stop all fluids"], answerIndex:1, explanation:"Trend weight/oedema suggests fluid overload—assess, consider diuretic review, safety-net and escalate appropriately." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Hypertension", q:"Which lifestyle advice is most evidence-aligned for long-term BP control?", choices:["High salt diet","Regular activity + lower salt + healthy weight","Avoid all carbs","Only drink energy drinks"], answerIndex:1, explanation:"Lifestyle fundamentals: salt reduction, activity, weight management, alcohol moderation, smoking cessation." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Atrial fibrillation", q:"A patient with AF asks why anticoagulants matter. Best explanation?", choices:["They lower heart rate","They prevent stroke risk from clots","They cure AF","They treat chest infections"], answerIndex:1, explanation:"AF increases stroke risk due to thrombus formation; anticoagulation reduces this risk." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Anticoagulation safety", q:"A warfarin patient has an INR above therapeutic range. Priority?", choices:["Give extra warfarin","Hold/adjust per protocol and escalate; check bleeding signs","Ignore","Give aspirin"], answerIndex:1, explanation:"High INR increases bleeding risk—follow local protocol and assess bleeding." },

  // Acute
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"ACS prioritisation", q:"Patient has central chest pain, sweaty, nauseated. Priority nursing action?", choices:["Offer antacid and wait","Obtain ECG urgently and escalate per pathway","Ask them to walk to relieve stress","Give food"], answerIndex:1, explanation:"Suspected ACS is time-critical: ECG + escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Shock basics", q:"Which observation pattern suggests poor perfusion?", choices:["Warm peripheries, bounding pulse","Cool clammy skin, delayed cap refill, hypotension","Normal urine output and BP","High appetite"], answerIndex:1, explanation:"Low perfusion signs: cool clammy skin, delayed refill, hypotension, reduced urine output." }
);
window.QUESTION_BANK.push(
  // ===== LTC: Heart failure / HTN / AF / anticoags / oedema =====
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Heart failure education", q:"Which self-monitoring advice is most useful for a patient with chronic heart failure?", choices:["Check weight daily and report rapid gain","Avoid all fluids forever","Take extra diuretic doses without advice","Only monitor BP once a month"], answerIndex:0, explanation:"Daily weights help detect fluid retention early; safety-net for rapid gains." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Heart failure symptoms", q:"Which symptom pattern most suggests worsening chronic heart failure?", choices:["Improving exercise tolerance","New orthopnoea and paroxysmal nocturnal dyspnoea","Tingling in fingers after cold","Itchy scalp"], answerIndex:1, explanation:"Orthopnoea/PND indicate pulmonary congestion and worsening HF." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Oedema differentials", q:"Bilateral ankle oedema is most consistent with:", choices:["Local sprain only","Systemic cause such as HF/renal/liver disease","Always DVT","Always cellulitis"], answerIndex:1, explanation:"Bilateral oedema suggests systemic causes; unilateral oedema raises DVT/cellulitis concerns." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Hypertension lifestyle", q:"Which advice best supports long-term BP control?", choices:["Increase salt for energy","Reduce salt + regular activity + healthy weight","Stop all carbs permanently","Skip medications when BP feels normal"], answerIndex:1, explanation:"Core lifestyle changes: salt reduction, activity, weight management and adherence." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Postural hypotension", q:"A patient feels dizzy on standing after a BP med increase. Best nursing action?", choices:["Tell them it’s normal and ignore","Check lying/standing BP, falls risk, and escalate for review","Encourage rapid standing practice","Give caffeine immediately"], answerIndex:1, explanation:"Assess for postural hypotension and falls risk; escalate for medication review." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"AF education", q:"Why does atrial fibrillation increase stroke risk?", choices:["It causes low potassium","It can form clots in the atria that can embolise","It always causes chest infections","It thickens blood vessels"], answerIndex:1, explanation:"AF causes atrial stasis → thrombus formation → embolic stroke risk." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Anticoag safety", q:"Which is the most appropriate safety advice for a patient on anticoagulants?", choices:["Ignore bruising","Report unusual bleeding/bruising and avoid double-dosing","Stop the drug if you feel tired","Take NSAIDs freely for pain"], answerIndex:1, explanation:"Bleeding risk + interactions; NSAIDs increase bleeding risk—follow local guidance." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Statins", q:"Statins are primarily used long-term to:", choices:["Treat acute pain","Reduce cardiovascular risk by lowering LDL cholesterol","Increase heart rate","Cure atrial fibrillation"], answerIndex:1, explanation:"Statins reduce LDL and cardiovascular risk long term." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Peripheral arterial disease", q:"Which symptom suggests peripheral arterial disease rather than venous disease?", choices:["Leg swelling worse at end of day","Intermittent claudication (pain on walking relieved by rest)","Itchy eczema around ankles","Varicose veins"], answerIndex:1, explanation:"PAD: exertional pain relieved by rest; venous disease often swelling/skin changes." },

  // ===== ACUTE: ACS / pulmonary oedema / shock / arrhythmias basics =====
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"ACS prioritisation", q:"A patient with suspected ACS—what comes first?", choices:["Offer a hot drink","ABCDE + urgent ECG and escalation","Wait for family to arrive","Encourage walking"], answerIndex:1, explanation:"Stabilise first (ABCDE) then ECG and escalation are time-critical." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Pulmonary oedema", q:"A patient is acutely breathless with crackles and pink frothy sputum. Best immediate action?", choices:["Lay them flat","Sit upright, give oxygen if hypoxic, and escalate urgently","Give oral fluids","Send them to shower"], answerIndex:1, explanation:"Pulmonary oedema is an emergency; upright positioning + urgent escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Shock recognition", q:"Which set of signs most suggests shock?", choices:["Warm skin, normal cap refill","Cool clammy skin, hypotension, reduced urine output","High appetite and thirst","Itchy rash only"], answerIndex:1, explanation:"Shock = poor perfusion: cool clammy skin, hypotension, oliguria, altered mental state." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Bradycardia", q:"A patient is very bradycardic and dizzy. Priority nursing response?", choices:["Ignore if young","Assess ABCDE, check BP/perfusion, and escalate urgently","Give a snack and wait","Walk them around"], answerIndex:1, explanation:"Symptomatic bradycardia can compromise perfusion—ABCDE and escalate." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Bleeding risk", q:"A patient on anticoagulants has black tarry stools. Best action?", choices:["Reassure","Escalate urgently for GI bleed assessment","Tell them to stop eating","Give ibuprofen"], answerIndex:1, explanation:"Melaena suggests GI bleed—urgent escalation needed." }
);
window.QUESTION_BANK.push(
  // ===== LTC: HF, HTN, AF, IHD risk, oedema =====
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF monitoring", q:"Which daily measure is most useful to detect fluid retention in HF?", choices:["Temperature only","Daily weight","Pupil size","Respiratory rate once a week"], answerIndex:1, explanation:"Daily weight trend detects fluid retention early." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF red flags", q:"Which symptom should prompt earlier review in chronic HF?", choices:["Stable mild fatigue","Rapid weight gain and worsening breathlessness","Mild itch","Occasional sneeze"], answerIndex:1, explanation:"Rapid weight gain + dyspnoea suggests fluid overload and deterioration." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF lifestyle", q:"Which advice best supports HF symptom control?", choices:["High salt diet","Limit excess salt and follow fluid advice if prescribed","Stop all walking","Skip meds if feeling fine"], answerIndex:1, explanation:"Salt management reduces fluid retention; adherence matters." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Stable angina", q:"Stable angina is typically:", choices:["Chest pain at rest always","Predictable chest discomfort on exertion relieved by rest","Always caused by infection","Cured by antibiotics"], answerIndex:1, explanation:"Stable angina is exertional and relieved by rest/GTN." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Statins", q:"Why are statins used long-term in cardiovascular disease?", choices:["To treat acute breathlessness","To lower LDL and reduce future cardiovascular events","To raise blood pressure","To cure arrhythmias"], answerIndex:1, explanation:"Statins reduce atherosclerotic risk and future events." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"AF symptoms", q:"A patient with AF reports palpitations and fatigue. Best nursing approach?", choices:["Ignore","Assess symptoms, pulse, BP; escalate for rate/rhythm control review","Give sugary drinks","Tell them to stop all meds"], answerIndex:1, explanation:"AF can reduce cardiac output; assess and support review." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Anticoag interactions", q:"Which OTC medicine should be used cautiously with anticoagulants?", choices:["Paracetamol (as advised)","Ibuprofen/NSAIDs","Water","Milk"], answerIndex:1, explanation:"NSAIDs increase bleeding risk—use cautiously and follow guidance." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Postural hypotension", q:"Most appropriate first step for suspected postural hypotension?", choices:["Check lying and standing BP","Give antibiotics","Restrict fluids completely","Start oxygen"], answerIndex:0, explanation:"Confirm with lying/standing BP; assess falls risk and meds." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"PAD vs venous", q:"Which finding supports peripheral arterial disease?", choices:["Warm swollen ankles with eczema","Cold foot with reduced pulses and pain on walking","Bilateral oedema only","Itchy scalp"], answerIndex:1, explanation:"PAD: reduced pulses, cold limb, claudication." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"DVT vs systemic oedema", q:"Unilateral leg swelling and pain is most concerning for:", choices:["Heart failure","DVT","Normal ageing","Anaemia"], answerIndex:1, explanation:"Unilateral swelling/pain raises concern for DVT and needs pathway assessment." },

  // ===== ACUTE: ACS, shock, arrhythmia signs, bleeding =====
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"ACS escalation", q:"A patient has new central chest pain and looks unwell. Priority?", choices:["Document later","ABCDE, urgent ECG, escalate per ACS pathway","Offer a walk","Give hot tea"], answerIndex:1, explanation:"Stabilise and diagnose quickly; ECG time-critical." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Shock types", q:"Septic shock most commonly causes:", choices:["Warm peripheries early, hypotension, tachycardia","Bradycardia and hypertension","Only ankle swelling","Only rash"], answerIndex:0, explanation:"Early sepsis may be warm shock with hypotension and tachycardia." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Bleeding", q:"A patient on anticoagulants vomits blood. Best action?", choices:["Reassure","Escalate urgently for GI bleed assessment","Give NSAID pain relief","Tell them to sleep"], answerIndex:1, explanation:"Haematemesis is a red flag—urgent escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Pulmonary oedema", q:"Acute pulmonary oedema: which position helps most initially?", choices:["Supine flat","Upright sitting","Head down tilt","Prone"], answerIndex:1, explanation:"Upright reduces venous return and improves ventilation." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Perfusion", q:"Which is a key marker of organ perfusion?", choices:["Urine output trend","Hair colour","Nail length","Vision sharpness"], answerIndex:0, explanation:"Urine output reflects renal perfusion and overall perfusion status." }
);
window.QUESTION_BANK.push(
  // ===== HF: LTC management, monitoring, escalation =====
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF fluid overload", q:"Which finding best suggests fluid overload in HF?", choices:["Dry mucous membranes","Weight gain + oedema + breathlessness","Postural dizziness only","Low appetite only"], answerIndex:1, explanation:"Fluid overload typically causes weight gain, oedema and worsening dyspnoea." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF self-care", q:"Which patient plan best supports HF self-care?", choices:["“I’ll weigh weekly only.”","“I’ll weigh daily, take meds as prescribed, and report rapid gains.”","“I’ll stop meds when symptoms improve.”","“I’ll increase salt to feel better.”"], answerIndex:1, explanation:"Daily weights + adherence + safety-netting reduce deterioration risk." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF breathlessness", q:"Orthopnoea in HF is best described as:", choices:["Breathlessness improved lying flat","Breathlessness worsens lying flat and improves sitting up","Only cough at night","Only breathlessness after meals"], answerIndex:1, explanation:"Orthopnoea is breathlessness when lying flat due to pulmonary congestion." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF meds monitoring", q:"A patient on diuretics should be monitored for:", choices:["Electrolyte imbalance and dehydration","Always high fever","Improved hearing","Hair loss"], answerIndex:0, explanation:"Diuretics can affect potassium, sodium and volume status—monitor U&Es and symptoms." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF escalation", q:"HF patient reports waking at night gasping for air (PND). Best action?", choices:["Reassure it’s normal","Escalate for urgent review as this may indicate worsening HF","Advise vigorous exercise overnight","Stop fluids completely"], answerIndex:1, explanation:"PND suggests pulmonary congestion and worsening HF—needs review." },

  // ===== HTN: long-term safety and adherence =====
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HTN adherence", q:"A patient says they stop BP meds when readings improve. Best response?", choices:["Agree","Explain BP control requires ongoing treatment; stopping increases stroke/MI risk","Tell them to double dose next time","Stop all monitoring"], answerIndex:1, explanation:"Hypertension often asymptomatic; ongoing treatment reduces future risk." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HTN lifestyle", q:"Which diet change supports BP reduction?", choices:["Increase salt","Reduce salt and processed foods","Only eat sweets","Avoid all fruit"], answerIndex:1, explanation:"Lower salt intake supports BP control." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Postural hypotension", q:"BP meds patient feels dizzy standing. Best immediate nursing check?", choices:["Random glucose only","Lying and standing BP + falls risk assessment","Peak flow","Ear exam"], answerIndex:1, explanation:"Check postural drop and falls risk; escalate for med review." },

  // ===== AF + anticoagulation: LTC safety =====
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"AF stroke prevention", q:"Which intervention reduces stroke risk in AF?", choices:["Anticoagulation when indicated","Antibiotics","Cough syrup","Vitamin C only"], answerIndex:0, explanation:"Anticoagulation reduces embolic stroke risk in AF when indicated." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Anticoag bleeding signs", q:"Which symptom should be reported promptly on anticoagulants?", choices:["Occasional mild bruise","Nosebleeds that don’t stop or blood in urine/stool","Mild thirst","Dry skin"], answerIndex:1, explanation:"Unusual/prolonged bleeding or haematuria/melaena requires review." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Anticoag safety", q:"Best advice if a patient misses an anticoagulant dose?", choices:["Double the next dose automatically","Follow medication instructions; don’t double-dose without advice","Stop the medication completely","Take NSAIDs for safety"], answerIndex:1, explanation:"Avoid double-dosing; follow guidance and consult prescriber/pharmacist if unsure." },

  // ===== Acute cardio: escalation priorities =====
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Chest pain triage", q:"Two patients: (A) chest pain + sweating; (B) swollen ankles stable. Who first?", choices:["B first","A first","Neither","Do paperwork"], answerIndex:1, explanation:"Chest pain with autonomic symptoms suggests ACS—time-critical." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Acute bleeding", q:"Patient on anticoagulants with sudden severe headache + neuro signs. Concern is:", choices:["Migraine only","Intracranial bleed—urgent escalation","Hay fever","Dehydration only"], answerIndex:1, explanation:"Anticoagulation increases bleeding risk; neuro symptoms can indicate intracranial haemorrhage." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Shock recognition", q:"Which is most consistent with poor perfusion?", choices:["Warm peripheries and bounding pulse always","Cool clammy skin and delayed cap refill","Normal urine output","Normal mental state always"], answerIndex:1, explanation:"Poor perfusion signs: cool clammy skin, delayed cap refill, hypotension, oliguria." }
);
window.QUESTION_BANK.push(
  // ===== HF: meds monitoring & patient education =====
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Diuretics monitoring", q:"A patient on loop diuretics develops cramps/weakness. What should you suspect and do?", choices:["Hyperkalaemia—ignore","Hypokalaemia—check U&Es and escalate for review","Normal effect—no action","Give salt tablets"], answerIndex:1, explanation:"Loop diuretics can lower potassium; symptoms warrant U&Es and review." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF patient education", q:"Which statement shows good HF understanding?", choices:["“Salt doesn’t matter.”","“I’ll monitor weight and swelling and report rapid changes.”","“I’ll stop meds when I feel well.”","“Breathlessness at rest is normal for me.”"], answerIndex:1, explanation:"Monitoring and early escalation reduce decompensation risk." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Fluid restriction", q:"If a fluid restriction is prescribed, the best nursing approach is:", choices:["Ignore it","Educate, help plan intake, and document intake/output","Only restrict water not other fluids","Keep it secret"], answerIndex:1, explanation:"Support adherence with planning and accurate documentation." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HF red flags", q:"Which symptom warrants urgent HF review?", choices:["Mild stable fatigue","New rest breathlessness or frothy sputum","Occasional sneeze","Dry skin"], answerIndex:1, explanation:"Rest breathlessness/frothy sputum suggests pulmonary oedema—urgent." },

  // ===== HTN: safety, adherence, complications =====
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HTN risks", q:"Long-term uncontrolled hypertension increases risk of:", choices:["Only sore throat","Stroke, MI, kidney damage","Improved memory","Reduced CV risk"], answerIndex:1, explanation:"HTN damages vessels/organs—major risk for stroke/MI/CKD." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"HTN lifestyle", q:"Which change can support BP reduction?", choices:["Increase alcohol intake","Reduce alcohol, stop smoking, be active, reduce salt","Only take vitamins","Avoid sleep"], answerIndex:1, explanation:"Lifestyle changes reduce BP and cardiovascular risk." },

  // ===== AF & anticoagulation: counselling and safety =====
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"AF pulse", q:"AF often produces what pulse pattern?", choices:["Regular and slow always","Irregularly irregular pulse","Only tachycardia","Only bradycardia"], answerIndex:1, explanation:"AF classically causes an irregularly irregular rhythm/pulse." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Anticoag counselling", q:"Best advice about NSAIDs when on anticoagulants?", choices:["They are always safe","Avoid/limit due to bleeding risk; seek advice for pain options","Take double dose","Only take on empty stomach"], answerIndex:1, explanation:"NSAIDs increase bleeding risk; use safer alternatives per guidance." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Bleeding red flags", q:"Which is a red flag while taking anticoagulants?", choices:["Small bruise after bump","Black tarry stools or vomiting blood","Mild thirst","Dry lips"], answerIndex:1, explanation:"Melaena/haematemesis indicates GI bleed risk—urgent review." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Anticoag adherence", q:"Why is consistent anticoagulant use important?", choices:["It improves appetite","Missed doses can increase clot/stroke risk","It cures AF","It stops infections"], answerIndex:1, explanation:"Inconsistent dosing reduces protection from thrombosis/stroke." },

  // ===== Acute: prioritisation scenarios =====
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Prioritisation", q:"Two patients: (A) new chest pain + sweating; (B) chronic ankle oedema stable. Who first?", choices:["B first","A first","Neither","Wait for doctor"], answerIndex:1, explanation:"Possible ACS is time-critical—assess first." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Deterioration", q:"HF patient suddenly becomes very breathless with crackles. Best immediate nursing response?", choices:["Lay flat","Sit upright, apply oxygen if hypoxic, escalate urgently","Offer food","Encourage walking"], answerIndex:1, explanation:"Likely pulmonary oedema; positioning + oxygen (if hypoxic) + urgent escalation." }
);
