window.QUESTION_BANK = window.QUESTION_BANK || [];

window.QUESTION_BANK.push(
  // LTC COPD/asthma
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"COPD long-term", q:"A COPD patient asks why inhaler technique matters. Best answer?", choices:["It doesn’t matter","Correct technique ensures drug reaches the lungs and reduces symptoms/exacerbations","It only helps taste","It replaces antibiotics"], answerIndex:1, explanation:"Technique directly affects deposition and control; poor technique = poor control." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"COPD O2 targets", q:"For COPD at risk of CO₂ retention, typical target SpO₂ is:", choices:["88–92%","94–98%","80–85%","99–100%"], answerIndex:0, explanation:"Common target for hypercapnic risk COPD is 88–92% unless directed otherwise." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Asthma control", q:"Which suggests poor long-term asthma control?", choices:["Inhaler use rarely","Frequent reliever use and night waking","Normal peak flow","No symptoms on exertion"], answerIndex:1, explanation:"Frequent reliever use and night symptoms suggest poor control and need review." },

  // Acute exacerbations
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Asthma red flags", q:"A severe asthma patient now has a ‘silent chest’. What does this indicate?", choices:["Improvement","Life-threatening asthma with minimal airflow","Normal finding","Mild anxiety"], answerIndex:1, explanation:"Silent chest can mean minimal ventilation—urgent escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"ABG interpretation", q:"ABG: pH 7.30, PaCO₂ 7.2 kPa (high), HCO₃⁻ 26. Interpretation?", choices:["Respiratory acidosis (acute)","Metabolic acidosis","Resp alkalosis","Met alkalosis"], answerIndex:0, explanation:"Low pH + high CO₂ with normal HCO₃ suggests acute respiratory acidosis." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"PE suspicion", q:"Sudden pleuritic chest pain + dyspnoea + tachycardia—best action?", choices:["Reassure and discharge","Escalate urgently for PE assessment pathway","Give antacid","Wait for morning round"], answerIndex:1, explanation:"PE is time-critical—escalate promptly." }
);
window.QUESTION_BANK.push(
  // ===== LTC: COPD/asthma maintenance, inhalers, rehab, smoking =====
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Inhaler technique", q:"What is the key reason to check inhaler technique regularly?", choices:["To improve taste","Poor technique reduces drug delivery and control","It replaces antibiotics","It stops all side effects"], answerIndex:1, explanation:"Technique affects deposition; poor technique = poor control and more exacerbations." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"COPD management", q:"Pulmonary rehabilitation mainly helps by:", choices:["Curing COPD","Improving exercise tolerance and breathlessness management","Replacing inhalers","Increasing infection risk"], answerIndex:1, explanation:"Pulmonary rehab improves function, symptoms and quality of life in COPD." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Smoking cessation", q:"Which statement best reflects smoking cessation advice in COPD/asthma?", choices:["It’s too late to help","Stopping smoking slows disease progression and improves outcomes","Only vaping helps","Cutting down has no value"], answerIndex:1, explanation:"Smoking cessation is the single most effective intervention to slow COPD progression." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Asthma prevention", q:"Which factor commonly triggers asthma symptoms long-term?", choices:["Regular controller inhaler use","Viral infections, allergens, exercise, smoke exposure","Drinking water","Sleeping"], answerIndex:1, explanation:"Common triggers include infections, allergens, smoke, cold air, exercise." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Peak flow", q:"Peak flow monitoring is most useful for:", choices:["Diagnosing all pneumonia","Tracking asthma control and early deterioration","Measuring kidney function","Treating heart failure"], answerIndex:1, explanation:"Peak flow can help detect asthma deterioration and response to treatment." },

  // ===== ACUTE: devices, exacerbations, pneumonia, ABG patterns =====
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Oxygen devices", q:"A non-rebreather mask is typically used when:", choices:["No oxygen needed","High concentration oxygen is required urgently","Patient needs humidity only","For long-term home oxygen titration"], answerIndex:1, explanation:"Non-rebreather delivers high concentration oxygen in acute hypoxia situations (per local policy)." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"COPD exacerbation", q:"COPD patient with increased sputum, wheeze, and dyspnoea—priority nursing approach?", choices:["Ignore if afebrile","ABCDE, check sats, target oxygen appropriately, escalate for review","Give large volumes of IV fluid immediately","Put them flat"], answerIndex:1, explanation:"Assess and stabilise first; titrate oxygen and escalate for treatment." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Pneumonia signs", q:"Which feature most supports pneumonia?", choices:["Runny nose only","Fever, cough, pleuritic pain, crackles, raised RR","Itchy skin","Back pain only"], answerIndex:1, explanation:"Pneumonia commonly presents with cough, fever, pleuritic pain, crackles, tachypnoea." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"ABG interpretation", q:"ABG: pH 7.48, PaCO₂ 4.0 (low), HCO₃⁻ 24. Interpretation?", choices:["Respiratory alkalosis (acute)","Metabolic alkalosis","Respiratory acidosis","Metabolic acidosis"], answerIndex:0, explanation:"High pH + low CO2 with normal bicarb suggests acute respiratory alkalosis." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Work of breathing", q:"Which finding suggests increased work of breathing?", choices:["Accessory muscle use and inability to speak full sentences","Slow RR 10 and calm speech","Warm hands only","Normal sats and normal RR"], answerIndex:0, explanation:"Accessory muscle use and limited speech indicate respiratory distress." }
);
window.QUESTION_BANK.push(
  // ===== LTC: COPD long-term management =====
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"COPD maintenance", q:"A COPD patient asks what long-term action most slows disease progression. Best answer?", choices:["More antibiotics","Stop smoking","Avoid all exercise","Drink more milk"], answerIndex:1, explanation:"Smoking cessation is the most effective intervention to slow COPD progression." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"COPD inhalers", q:"What is the main purpose of maintenance inhalers in COPD?", choices:["Cure COPD","Reduce symptoms and exacerbations by improving airflow","Replace oxygen therapy","Treat pneumonia"], answerIndex:1, explanation:"Maintenance inhalers improve airflow, reduce breathlessness and exacerbations." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"COPD education", q:"Which statement shows good understanding of COPD self-management?", choices:["“I’ll stop inhalers when I feel better.”","“I’ll use inhalers as prescribed and watch for changes in sputum/breathlessness.”","“I should avoid moving to save my lungs.”","“Antibiotics fix COPD permanently.”"], answerIndex:1, explanation:"Adherence + symptom monitoring supports control and early escalation." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Breathlessness techniques", q:"Pursed-lip breathing mainly helps by:", choices:["Increasing panic","Reducing air trapping and improving exhalation","Curing asthma","Lowering blood sugar"], answerIndex:1, explanation:"It prolongs exhalation and can reduce dynamic hyperinflation." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Pulmonary rehab", q:"Which outcome is most associated with pulmonary rehabilitation?", choices:["Worsened exercise tolerance","Improved exercise capacity and quality of life","Guaranteed smoking cessation","Cure of COPD"], answerIndex:1, explanation:"Pulmonary rehab improves function and breathlessness management." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Vaccination", q:"Which vaccines are commonly recommended for COPD long-term risk reduction?", choices:["None help","Influenza and pneumococcal vaccines (per policy)","Only travel vaccines","Only childhood vaccines"], answerIndex:1, explanation:"Vaccination reduces risk/severity of respiratory infections and exacerbations." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Inhaler technique", q:"Which is the best nursing approach to inhaler technique support?", choices:["Assume they know","Ask them to demonstrate and correct errors","Only give a leaflet","Tell them to use it more"], answerIndex:1, explanation:"Teach-back by demonstration is the most effective check." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Spacer use", q:"A spacer is useful because it:", choices:["Makes inhalers taste nicer","Improves drug delivery to lungs and reduces oropharyngeal deposition","Replaces inhalers","Only helps children"], answerIndex:1, explanation:"Spacers improve deposition and reduce local side effects." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"ICS mouth care", q:"After using an inhaled corticosteroid, the patient should:", choices:["Lie flat","Rinse mouth/spit to reduce oral thrush risk","Skip next dose","Take antibiotics"], answerIndex:1, explanation:"Rinsing reduces oral candidiasis risk." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Asthma control", q:"Which suggests good long-term asthma control?", choices:["Night waking weekly","Reliever used daily","Minimal symptoms and reliever use <2x/week","Frequent wheeze with exercise"], answerIndex:2, explanation:"Low symptom burden and infrequent reliever use suggest control." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Asthma plan", q:"Why is a personalised asthma action plan important?", choices:["It replaces medical review","It guides self-management and when to escalate","It stops all triggers","It reduces need for inhalers"], answerIndex:1, explanation:"Plans support early escalation and appropriate action during deterioration." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Sleep apnoea", q:"A key long-term risk of untreated obstructive sleep apnoea is:", choices:["Lower BP always","Hypertension and cardiovascular disease risk","Cure of diabetes","Improved alertness"], answerIndex:1, explanation:"OSA is linked to hypertension and increased cardiovascular risk." },

  // ===== ACUTE: oxygen, exacerbations, pneumonia, PE, ABG =====
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Oxygen safety", q:"A patient becomes suddenly hypoxic. Most appropriate immediate action?", choices:["Wait for next obs round","Assess ABCDE and apply oxygen per policy while escalating","Offer food","Ask them to sleep"], answerIndex:1, explanation:"Treat hypoxia urgently while escalating and assessing cause." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Work of breathing", q:"Which is most concerning for impending respiratory failure?", choices:["Able to speak full sentences","Silent chest and exhaustion","Mild cough only","Normal RR"], answerIndex:1, explanation:"Exhaustion/silent chest can indicate failing ventilation." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"COPD exacerbation", q:"COPD patient with SpO₂ 85% on air. Best approach?", choices:["Target sats 94–98% immediately","Give oxygen and aim 88–92% if at risk of CO₂ retention; escalate","Avoid oxygen completely","Give a sugary drink"], answerIndex:1, explanation:"Titrate oxygen to appropriate target and escalate." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Asthma deterioration", q:"Which is a red flag requiring urgent escalation in asthma?", choices:["Reliever helps fully","Can’t speak in full sentences","Mild runny nose","Slight cough"], answerIndex:1, explanation:"Speech limitation indicates severe attack and urgent escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Pneumonia deterioration", q:"A pneumonia patient becomes increasingly confused with rising RR. Best action?", choices:["Reassure","Escalate urgently; assess for sepsis/hypoxia","Offer dessert","Delay until morning"], answerIndex:1, explanation:"Confusion + tachypnoea may indicate sepsis/hypoxia—urgent escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"PE red flags", q:"Which combination most suggests pulmonary embolism?", choices:["Dyspnoea + pleuritic pain + tachycardia","Sore throat only","Headache only","Itchy rash only"], answerIndex:0, explanation:"Classic PE features warrant urgent pathway assessment." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"ABG", q:"ABG: pH 7.28, PaCO₂ 7.5 (high), HCO₃⁻ 28 (high). Best interpretation?", choices:["Acute respiratory acidosis","Compensated (chronic) respiratory acidosis","Metabolic acidosis","Respiratory alkalosis"], answerIndex:1, explanation:"Acidaemia with high CO₂ and elevated bicarb suggests compensation (chronic/partly compensated)." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"ABG", q:"ABG: pH 7.50, PaCO₂ 6.8 (high), HCO₃⁻ 34 (high). Interpretation?", choices:["Metabolic alkalosis with respiratory compensation","Respiratory alkalosis","Metabolic acidosis","Acute respiratory acidosis"], answerIndex:0, explanation:"High pH with high HCO₃ indicates metabolic alkalosis; CO₂ rises as compensation." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"ABG", q:"ABG: pH 7.31, PaCO₂ 4.5 (normal/low), HCO₃⁻ 18 (low). Interpretation?", choices:["Metabolic acidosis","Respiratory acidosis","Respiratory alkalosis","Metabolic alkalosis"], answerIndex:0, explanation:"Low pH with low bicarb indicates metabolic acidosis (CO₂ may be low for compensation)." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Atelectasis prevention", q:"Post-op patient at risk of atelectasis. Best nursing intervention?", choices:["Encourage deep breathing/incentive spirometry and mobilisation","Keep them flat and still","Restrict fluids always","Avoid pain control"], answerIndex:0, explanation:"Deep breathing and mobilisation reduce atelectasis risk." }
);
