window.QUESTION_BANK = window.QUESTION_BANK || [];

window.QUESTION_BANK.push(
  // Safety / deterioration (mostly ACUTE)
  { pack:"Safety: Deterioration", track:"ACUTE", topic:"Clinical Deterioration", subtopic:"ABCDE", q:"You find a patient newly drowsy and clammy. What is your most appropriate first action?", choices:["Do a full history then examine","Start ABCDE and treat immediate life threats","Wait for a doctor before checking obs","Offer food and fluids"], answerIndex:1, explanation:"NMC-style prioritisation: ABCDE first to identify/treat life-threatening problems." },
  { pack:"Safety: Deterioration", track:"ACUTE", topic:"Clinical Deterioration", subtopic:"Escalation", q:"A patient’s RR rises to 30 with SpO₂ 89% on air. What is best?", choices:["Recheck in 30 minutes","Escalate urgently and give oxygen per policy if hypoxic","Give oral fluids","Encourage sleep"], answerIndex:1, explanation:"Hypoxia + tachypnoea requires urgent escalation and prompt support." },

  // Medicines management (LTC + ACUTE)
  { pack:"Safety: Medicines", track:"BOTH", topic:"Pharmacology Safety", subtopic:"5 Rights", q:"Which is essential before administering any medicine?", choices:["5 rights + allergy check + right documentation","Only check label once","Skip ID checks if you recognise them","Give first then document later"], answerIndex:0, explanation:"Safety basics: right patient/drug/dose/route/time + allergies and documentation." },
  { pack:"Safety: Medicines", track:"BOTH", topic:"Pharmacology Safety", subtopic:"Insulin", q:"Before giving insulin, you must check:", choices:["Blood glucose and meal timing/plan","Temperature only","Pain score only","Pulse only"], answerIndex:0, explanation:"Insulin can cause hypoglycaemia—check BG and ensure appropriate intake/timing." },
  { pack:"Safety: Medicines", track:"ACUTE", topic:"Pharmacology Safety", subtopic:"Opioids", q:"Patient is very drowsy with slow respirations after opioids. What is priority?", choices:["Give more opioid for pain","Escalate urgently and follow opioid toxicity protocol (naloxone may be required)","Send them to sleep","Give oral fluids"], answerIndex:1, explanation:"Respiratory depression is life-threatening. Escalate and follow local policy." },

  // Documentation / NMC professionalism (BOTH)
  { pack:"Safety: Documentation", track:"BOTH", topic:"Professional Practice", subtopic:"Documentation", q:"Best documentation approach after an incident?", choices:["Only document if asked","Document promptly, factually, and escalate per policy","Use opinions and blame","Document later from memory"], answerIndex:1, explanation:"NMC-aligned: timely, factual, objective documentation + escalation." }
);
window.QUESTION_BANK.push(
  // ===== NMC-style prioritisation patterns =====
  { pack:"Safety: Deterioration", track:"ACUTE", topic:"Clinical Deterioration", subtopic:"Prioritisation", q:"Two patients: (A) RR 30, SpO₂ 90% on air; (B) pain 8/10 with stable obs. Who first?", choices:["B first (pain)","A first (airway/breathing risk)","Do paperwork first","Wait for ward round"], answerIndex:1, explanation:"ABCDE: breathing compromise first, then pain once safe." },
  { pack:"Safety: Medicines", track:"BOTH", topic:"Pharmacology Safety", subtopic:"High-risk meds", q:"Why are insulin and anticoagulants considered high-risk medicines?", choices:["They taste bad","They have a higher risk of serious harm if errors occur","They treat infection","They are rarely used"], answerIndex:1, explanation:"Higher consequence if wrong dose/timing—require extra checks and monitoring." },
  { pack:"Safety: Documentation", track:"BOTH", topic:"Professional Practice", subtopic:"Escalation", q:"If you’re worried a patient is deteriorating but you’re not 100% sure, what is best?", choices:["Wait for certainty","Escalate concerns early and share objective observations","Only tell a colleague later","Write it privately"], answerIndex:1, explanation:"NMC safety culture: escalate early with objective data; don’t wait for deterioration." },
  { pack:"Safety: Infection", track:"BOTH", topic:"Immune/Lymphatic", subtopic:"PPE", q:"When should you perform hand hygiene?", choices:["Only after contact","Only before contact","Before and after patient contact and after glove removal","Only at start of shift"], answerIndex:2, explanation:"Hand hygiene before/after contact and after gloves reduces transmission." }
);
window.QUESTION_BANK.push(
  { pack:"Safety: Deterioration", track:"ACUTE", topic:"Clinical Deterioration", subtopic:"Escalation", q:"Which is the safest approach if you are concerned about deterioration?", choices:["Wait until the next obs set","Escalate early using objective observations and local policy","Only tell a friend","Assume it’s anxiety"], answerIndex:1, explanation:"NMC-aligned: escalate early, share objective data, and follow policy." },
  { pack:"Safety: Medicines", track:"BOTH", topic:"Pharmacology Safety", subtopic:"Allergy", q:"A patient reports previous anaphylaxis to penicillin. Best action?", choices:["Give it anyway with monitoring","Avoid penicillin and escalate for alternative choice per policy","Half the dose","Give with food"], answerIndex:1, explanation:"True anaphylaxis requires avoidance and safe alternative selection." },
  { pack:"Safety: Medicines", track:"BOTH", topic:"Pharmacology Safety", subtopic:"Double-checks", q:"Which situation most warrants an independent double-check (per typical policy)?", choices:["Low-risk topical cream","High-risk meds such as insulin/IV meds/anticoagulants","Moisturiser","Eye drops always"], answerIndex:1, explanation:"High-risk medicines often require independent checks—follow local policy." },
  { pack:"Safety: Documentation", track:"BOTH", topic:"Professional Practice", subtopic:"Record keeping", q:"Good record keeping means documentation should be:", choices:["Late and detailed opinions","Timely, factual, and clearly dated/signed","Only done weekly","Done by memory later"], answerIndex:1, explanation:"Document promptly and objectively; follow local record-keeping standards." }
);
