window.QUESTION_BANK = window.QUESTION_BANK || [];

window.QUESTION_BANK.push(
  // LTC (HF/HTN/AF/anticoags)
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Heart failure management", q:"A stable HF patient reports increasing ankle swelling and weight gain over a week. Best nursing action?", choices:["Ignore—common in HF","Assess fluid status, check weight trend, escalate for review/meds adjustment","Advise strenuous exercise immediately","Stop all fluids"], answerIndex:1, explanation:"Trend weight/oedema suggests fluid overload—assess, consider diuretic review, safety-net and escalate appropriately." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Hypertension", q:"Which lifestyle advice is most evidence-aligned for long-term BP control?", choices:["High salt diet","Regular activity + lower salt + healthy weight","Avoid all carbs","Only drink energy drinks"], answerIndex:1, explanation:"Lifestyle fundamentals: salt reduction, activity, weight management, alcohol moderation, smoking cessation." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Atrial fibrillation", q:"A patient with AF asks why anticoagulants matter. Best explanation?", choices:["They lower heart rate","They prevent stroke risk from clots","They cure AF","They treat chest infections"], answerIndex:1, explanation:"AF increases stroke risk due to thrombus formation; anticoagulation reduces this risk." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Anticoagulation safety", q:"A warfarin patient has an INR above therapeutic range. Priority?", choices:["Give extra warfarin","Hold/adjust per protocol and escalate; check bleeding signs","Ignore","Give aspirin"], answerIndex:1, explanation:"High INR increases bleeding risk—follow local protocol and assess bleeding." },

  // Acute
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"ACS prioritisation", q:"Patient has central chest pain, sweaty, nauseated. Priority nursing action?", choices:["Offer antacid and wait","Obtain ECG urgently and escalate per pathway","Ask them to walk to relieve stress","Give food"], answerIndex:1, explanation:"Suspected ACS is time-critical: ECG + escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Shock basics", q:"Which observation pattern suggests poor perfusion?", choices:["Warm peripheries, bounding pulse","Cool clammy skin, delayed cap refill, hypotension","Normal urine output and BP","High appetite"], answerIndex:1, explanation:"Low perfusion signs: cool clammy skin, delayed refill, hypotension, reduced urine output." }
);
window.QUESTION_BANK.push(
  // ===== LTC: Heart failure / HTN / AF / anticoags / oedema =====
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Heart failure education", q:"Which self-monitoring advice is most useful for a patient with chronic heart failure?", choices:["Check weight daily and report rapid gain","Avoid all fluids forever","Take extra diuretic doses without advice","Only monitor BP once a month"], answerIndex:0, explanation:"Daily weights help detect fluid retention early; safety-net for rapid gains." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Heart failure symptoms", q:"Which symptom pattern most suggests worsening chronic heart failure?", choices:["Improving exercise tolerance","New orthopnoea and paroxysmal nocturnal dyspnoea","Tingling in fingers after cold","Itchy scalp"], answerIndex:1, explanation:"Orthopnoea/PND indicate pulmonary congestion and worsening HF." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Oedema differentials", q:"Bilateral ankle oedema is most consistent with:", choices:["Local sprain only","Systemic cause such as HF/renal/liver disease","Always DVT","Always cellulitis"], answerIndex:1, explanation:"Bilateral oedema suggests systemic causes; unilateral oedema raises DVT/cellulitis concerns." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Hypertension lifestyle", q:"Which advice best supports long-term BP control?", choices:["Increase salt for energy","Reduce salt + regular activity + healthy weight","Stop all carbs permanently","Skip medications when BP feels normal"], answerIndex:1, explanation:"Core lifestyle changes: salt reduction, activity, weight management and adherence." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Postural hypotension", q:"A patient feels dizzy on standing after a BP med increase. Best nursing action?", choices:["Tell them it’s normal and ignore","Check lying/standing BP, falls risk, and escalate for review","Encourage rapid standing practice","Give caffeine immediately"], answerIndex:1, explanation:"Assess for postural hypotension and falls risk; escalate for medication review." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"AF education", q:"Why does atrial fibrillation increase stroke risk?", choices:["It causes low potassium","It can form clots in the atria that can embolise","It always causes chest infections","It thickens blood vessels"], answerIndex:1, explanation:"AF causes atrial stasis → thrombus formation → embolic stroke risk." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Anticoag safety", q:"Which is the most appropriate safety advice for a patient on anticoagulants?", choices:["Ignore bruising","Report unusual bleeding/bruising and avoid double-dosing","Stop the drug if you feel tired","Take NSAIDs freely for pain"], answerIndex:1, explanation:"Bleeding risk + interactions; NSAIDs increase bleeding risk—follow local guidance." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Statins", q:"Statins are primarily used long-term to:", choices:["Treat acute pain","Reduce cardiovascular risk by lowering LDL cholesterol","Increase heart rate","Cure atrial fibrillation"], answerIndex:1, explanation:"Statins reduce LDL and cardiovascular risk long term." },
  { pack:"Year 2", track:"LTC", topic:"Cardiovascular", subtopic:"Peripheral arterial disease", q:"Which symptom suggests peripheral arterial disease rather than venous disease?", choices:["Leg swelling worse at end of day","Intermittent claudication (pain on walking relieved by rest)","Itchy eczema around ankles","Varicose veins"], answerIndex:1, explanation:"PAD: exertional pain relieved by rest; venous disease often swelling/skin changes." },

  // ===== ACUTE: ACS / pulmonary oedema / shock / arrhythmias basics =====
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"ACS prioritisation", q:"A patient with suspected ACS—what comes first?", choices:["Offer a hot drink","ABCDE + urgent ECG and escalation","Wait for family to arrive","Encourage walking"], answerIndex:1, explanation:"Stabilise first (ABCDE) then ECG and escalation are time-critical." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Pulmonary oedema", q:"A patient is acutely breathless with crackles and pink frothy sputum. Best immediate action?", choices:["Lay them flat","Sit upright, give oxygen if hypoxic, and escalate urgently","Give oral fluids","Send them to shower"], answerIndex:1, explanation:"Pulmonary oedema is an emergency; upright positioning + urgent escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Shock recognition", q:"Which set of signs most suggests shock?", choices:["Warm skin, normal cap refill","Cool clammy skin, hypotension, reduced urine output","High appetite and thirst","Itchy rash only"], answerIndex:1, explanation:"Shock = poor perfusion: cool clammy skin, hypotension, oliguria, altered mental state." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Bradycardia", q:"A patient is very bradycardic and dizzy. Priority nursing response?", choices:["Ignore if young","Assess ABCDE, check BP/perfusion, and escalate urgently","Give a snack and wait","Walk them around"], answerIndex:1, explanation:"Symptomatic bradycardia can compromise perfusion—ABCDE and escalate." },
  { pack:"Year 2", track:"ACUTE", topic:"Cardiovascular", subtopic:"Bleeding risk", q:"A patient on anticoagulants has black tarry stools. Best action?", choices:["Reassure","Escalate urgently for GI bleed assessment","Tell them to stop eating","Give ibuprofen"], answerIndex:1, explanation:"Melaena suggests GI bleed—urgent escalation needed." }
);
