window.QUESTION_BANK = window.QUESTION_BANK || [];

window.QUESTION_BANK.push(
  // LTC CKD/electrolytes
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"CKD monitoring", q:"Which trend is most useful for ongoing CKD monitoring in practice?", choices:["One-off urine dip only","eGFR trend + UACR + BP control","Temperature checks only","Random pain scores"], answerIndex:1, explanation:"CKD monitoring focuses on kidney function trend, proteinuria, and BP control." },
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"Diuretics & potassium", q:"Patient on loop diuretic has muscle weakness/cramps. What do you suspect?", choices:["Hyperkalaemia","Hypokalaemia","Hypercalcaemia","Hyponatraemia always"], answerIndex:1, explanation:"Loop diuretics can cause potassium loss → cramps/weakness; check U&Es." },

  // Acute AKI
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"AKI recognition", q:"Best immediate indicator of worsening AKI at bedside?", choices:["Urine output trend","Hair loss","Bowel habit","Skin colour only"], answerIndex:0, explanation:"Urine output trend is a key clinical indicator alongside U&Es." },
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"Hyperkalaemia risk", q:"Which electrolyte issue is most associated with lethal arrhythmias?", choices:["Hyperkalaemia","Hyponatraemia","Low phosphate","High chloride"], answerIndex:0, explanation:"Hyperkalaemia can trigger fatal arrhythmias—urgent escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"Fluid status", q:"Which finding best fits fluid overload?", choices:["Dry mucous membranes","Weight gain + oedema","Postural dizziness","Poor skin turgor"], answerIndex:1, explanation:"Overload causes weight gain, oedema, raised JVP, crackles." }
);
window.QUESTION_BANK.push(
  // ===== LTC: CKD, BP/proteinuria, meds, fluid/electrolytes =====
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"CKD and BP", q:"Why is BP control important in CKD?", choices:["It has no effect","It helps slow progression and reduces cardiovascular risk","It cures CKD","It prevents all UTIs"], answerIndex:1, explanation:"BP control reduces glomerular damage and lowers cardiovascular risk." },
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"Proteinuria", q:"Protein in urine (albuminuria) is clinically important because it:", choices:["Proves dehydration only","Indicates kidney damage and higher cardiovascular risk","Means infection always","Is normal in all adults"], answerIndex:1, explanation:"Albuminuria suggests kidney damage and higher cardiovascular risk." },
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"Sick day rules", q:"When unwell with vomiting/diarrhoea, which advice is most appropriate for CKD patients on multiple meds?", choices:["Take extra doses","Maintain hydration and seek review if unable to keep fluids down; follow local sick-day guidance","Stop all meds forever","Only eat salty foods"], answerIndex:1, explanation:"Risk of dehydration/AKI; follow local sick-day guidance and seek review." },
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"Electrolytes", q:"Which symptom cluster can fit hyponatraemia?", choices:["Confusion, headache, seizures in severe cases","Chest pain only","Jaundice only","Earache"], answerIndex:0, explanation:"Hyponatraemia can cause neurological symptoms due to cerebral oedema." },

  // ===== ACUTE: AKI triggers, urinary retention, UTI/pyelo red flags =====
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"AKI causes", q:"Which factor commonly contributes to AKI in hospital?", choices:["Adequate hydration","Dehydration, sepsis, nephrotoxic meds","Daily walking","High fibre diet"], answerIndex:1, explanation:"AKI often triggered by dehydration, sepsis, hypotension, nephrotoxins." },
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"Urinary retention", q:"Which finding suggests urinary retention?", choices:["Large urine output","Suprapubic discomfort/distension with small frequent voids","Itchy rash","Wheezing"], answerIndex:1, explanation:"Retention can present with suprapubic distension and small frequent voids/dribbling." },
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"Pyelonephritis", q:"Which symptom set suggests pyelonephritis rather than simple cystitis?", choices:["Dysuria only","Fever + flank pain + nausea/vomiting","Itchy scalp","Chronic cough"], answerIndex:1, explanation:"Upper UTI often causes fever and flank pain; needs escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"Hyperkalaemia escalation", q:"Which is the best immediate nursing response to suspected hyperkalaemia?", choices:["Wait for next shift","Escalate urgently, obtain ECG per protocol, and review meds/U&Es","Give high potassium foods","Encourage exercise"], answerIndex:1, explanation:"Hyperkalaemia can cause lethal arrhythmias—urgent escalation and ECG per protocol." }
);
window.QUESTION_BANK.push(
  // ===== LTC: CKD, electrolytes, fluid balance =====
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"CKD cardiovascular risk", q:"CKD increases cardiovascular risk because:", choices:["It lowers LDL always","It is associated with hypertension, vascular changes, and inflammation","It prevents diabetes","It cures HF"], answerIndex:1, explanation:"CKD is strongly linked to cardiovascular disease via multiple mechanisms." },
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"Fluid balance", q:"Which is most helpful for long-term fluid status monitoring?", choices:["One-off weight","Daily weight trend and input/output if indicated","Only appetite","Only temperature"], answerIndex:1, explanation:"Trends are more useful than single readings." },
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"Hyperkalaemia education", q:"Which food group is often discussed in hyperkalaemia education?", choices:["High potassium foods (e.g., bananas)","Only dairy always","Only water","Only bread"], answerIndex:0, explanation:"Dietary potassium advice may be needed—follow local renal diet guidance." },
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"Uraemia symptoms", q:"Which symptom can be seen in advanced kidney dysfunction?", choices:["Confusion/fatigue and pruritus","Improved energy only","Always fever","Only runny nose"], answerIndex:0, explanation:"Uraemia can cause fatigue, pruritus, nausea, confusion." },
  { pack:"Year 2", track:"LTC", topic:"Renal", subtopic:"Anaemia in CKD", q:"Why is anaemia common in CKD?", choices:["Too much vitamin C","Reduced erythropoietin production","Always blood loss","Too much insulin"], answerIndex:1, explanation:"Kidneys produce EPO; reduced EPO contributes to anaemia." },

  // ===== ACUTE: AKI recognition, dehydration, obstruction, UTI =====
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"AKI bundle", q:"A patient at risk of AKI—what is a key nursing priority?", choices:["Ignore urine output","Monitor urine output and hydration; avoid nephrotoxins and escalate changes","Give high protein supplements only","Stop all observations"], answerIndex:1, explanation:"AKI prevention/recognition includes UO monitoring, hydration, and nephrotoxin awareness." },
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"Dehydration signs", q:"Which indicates dehydration/hypovolaemia?", choices:["Weight gain and oedema","Dry mucous membranes and postural dizziness","Crackles and raised JVP","Hypertension with bradycardia"], answerIndex:1, explanation:"Dry mucosa and postural symptoms suggest hypovolaemia." },
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"Post-renal AKI", q:"A blocked catheter with low urine output is a risk for:", choices:["Post-renal AKI","Asthma attack","Stroke","Appendicitis"], answerIndex:0, explanation:"Obstruction can cause post-renal AKI—address promptly." },
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"UTI delirium", q:"Older adult with acute confusion and urinary symptoms—best response?", choices:["Normal ageing","Assess for infection/delirium causes and escalate for review","Ignore","Offer energy drink"], answerIndex:1, explanation:"Acute confusion is delirium until proven otherwise—investigate and escalate." },
  { pack:"Year 2", track:"ACUTE", topic:"Renal", subtopic:"Sepsis and kidneys", q:"Why can sepsis cause AKI?", choices:["It improves kidney perfusion","It reduces perfusion and triggers inflammatory injury","It only affects lungs","It increases urine output"], answerIndex:1, explanation:"Sepsis can reduce renal perfusion and cause inflammatory kidney injury." }
);
