window.QUESTION_BANK = window.QUESTION_BANK || [];

window.QUESTION_BANK.push(
  // LTC COPD/asthma
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"COPD long-term", q:"A COPD patient asks why inhaler technique matters. Best answer?", choices:["It doesn’t matter","Correct technique ensures drug reaches the lungs and reduces symptoms/exacerbations","It only helps taste","It replaces antibiotics"], answerIndex:1, explanation:"Technique directly affects deposition and control; poor technique = poor control." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"COPD O2 targets", q:"For COPD at risk of CO₂ retention, typical target SpO₂ is:", choices:["88–92%","94–98%","80–85%","99–100%"], answerIndex:0, explanation:"Common target for hypercapnic risk COPD is 88–92% unless directed otherwise." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Asthma control", q:"Which suggests poor long-term asthma control?", choices:["Inhaler use rarely","Frequent reliever use and night waking","Normal peak flow","No symptoms on exertion"], answerIndex:1, explanation:"Frequent reliever use and night symptoms suggest poor control and need review." },

  // Acute exacerbations
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Asthma red flags", q:"A severe asthma patient now has a ‘silent chest’. What does this indicate?", choices:["Improvement","Life-threatening asthma with minimal airflow","Normal finding","Mild anxiety"], answerIndex:1, explanation:"Silent chest can mean minimal ventilation—urgent escalation." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"ABG interpretation", q:"ABG: pH 7.30, PaCO₂ 7.2 kPa (high), HCO₃⁻ 26. Interpretation?", choices:["Respiratory acidosis (acute)","Metabolic acidosis","Resp alkalosis","Met alkalosis"], answerIndex:0, explanation:"Low pH + high CO₂ with normal HCO₃ suggests acute respiratory acidosis." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"PE suspicion", q:"Sudden pleuritic chest pain + dyspnoea + tachycardia—best action?", choices:["Reassure and discharge","Escalate urgently for PE assessment pathway","Give antacid","Wait for morning round"], answerIndex:1, explanation:"PE is time-critical—escalate promptly." }
);
window.QUESTION_BANK.push(
  // ===== LTC: COPD/asthma maintenance, inhalers, rehab, smoking =====
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Inhaler technique", q:"What is the key reason to check inhaler technique regularly?", choices:["To improve taste","Poor technique reduces drug delivery and control","It replaces antibiotics","It stops all side effects"], answerIndex:1, explanation:"Technique affects deposition; poor technique = poor control and more exacerbations." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"COPD management", q:"Pulmonary rehabilitation mainly helps by:", choices:["Curing COPD","Improving exercise tolerance and breathlessness management","Replacing inhalers","Increasing infection risk"], answerIndex:1, explanation:"Pulmonary rehab improves function, symptoms and quality of life in COPD." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Smoking cessation", q:"Which statement best reflects smoking cessation advice in COPD/asthma?", choices:["It’s too late to help","Stopping smoking slows disease progression and improves outcomes","Only vaping helps","Cutting down has no value"], answerIndex:1, explanation:"Smoking cessation is the single most effective intervention to slow COPD progression." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Asthma prevention", q:"Which factor commonly triggers asthma symptoms long-term?", choices:["Regular controller inhaler use","Viral infections, allergens, exercise, smoke exposure","Drinking water","Sleeping"], answerIndex:1, explanation:"Common triggers include infections, allergens, smoke, cold air, exercise." },
  { pack:"Year 2", track:"LTC", topic:"Respiratory", subtopic:"Peak flow", q:"Peak flow monitoring is most useful for:", choices:["Diagnosing all pneumonia","Tracking asthma control and early deterioration","Measuring kidney function","Treating heart failure"], answerIndex:1, explanation:"Peak flow can help detect asthma deterioration and response to treatment." },

  // ===== ACUTE: devices, exacerbations, pneumonia, ABG patterns =====
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Oxygen devices", q:"A non-rebreather mask is typically used when:", choices:["No oxygen needed","High concentration oxygen is required urgently","Patient needs humidity only","For long-term home oxygen titration"], answerIndex:1, explanation:"Non-rebreather delivers high concentration oxygen in acute hypoxia situations (per local policy)." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"COPD exacerbation", q:"COPD patient with increased sputum, wheeze, and dyspnoea—priority nursing approach?", choices:["Ignore if afebrile","ABCDE, check sats, target oxygen appropriately, escalate for review","Give large volumes of IV fluid immediately","Put them flat"], answerIndex:1, explanation:"Assess and stabilise first; titrate oxygen and escalate for treatment." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Pneumonia signs", q:"Which feature most supports pneumonia?", choices:["Runny nose only","Fever, cough, pleuritic pain, crackles, raised RR","Itchy skin","Back pain only"], answerIndex:1, explanation:"Pneumonia commonly presents with cough, fever, pleuritic pain, crackles, tachypnoea." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"ABG interpretation", q:"ABG: pH 7.48, PaCO₂ 4.0 (low), HCO₃⁻ 24. Interpretation?", choices:["Respiratory alkalosis (acute)","Metabolic alkalosis","Respiratory acidosis","Metabolic acidosis"], answerIndex:0, explanation:"High pH + low CO2 with normal bicarb suggests acute respiratory alkalosis." },
  { pack:"Year 2", track:"ACUTE", topic:"Respiratory", subtopic:"Work of breathing", q:"Which finding suggests increased work of breathing?", choices:["Accessory muscle use and inability to speak full sentences","Slow RR 10 and calm speech","Warm hands only","Normal sats and normal RR"], answerIndex:0, explanation:"Accessory muscle use and limited speech indicate respiratory distress." }
);
