window.QUESTION_BANK = window.QUESTION_BANK || [];

window.QUESTION_BANK.push(
  // LTC diabetes / thyroid
  { pack:"Year 2", track:"LTC", topic:"Endocrine", subtopic:"Diabetes long-term", q:"Which is a key long-term diabetes nursing focus to reduce complications?", choices:["Ignore feet unless painful","Foot checks + BP/lipids control + HbA1c monitoring + education","Only weigh monthly","Avoid all exercise"], answerIndex:1, explanation:"Complication reduction: glycaemic control, BP/lipids, foot care, education and adherence support." },
  { pack:"Year 2", track:"LTC", topic:"Endocrine", subtopic:"Steroids", q:"Steroids commonly increase risk of:", choices:["Hypoglycaemia","Hyperglycaemia","Low appetite only","Bradycardia"], answerIndex:1, explanation:"Glucocorticoids can raise blood glucose—monitor BMs." },

  // Acute DKA/HHS and GI bleeds
  { pack:"Year 2", track:"ACUTE", topic:"Endocrine", subtopic:"Hypoglycaemia", q:"Which finding suggests hypoglycaemia?", choices:["Warm dry skin","Sweating + tremor + confusion","Fruity breath","Kussmaul breathing"], answerIndex:1, explanation:"Adrenergic + neuroglycopenic symptoms suggest hypoglycaemia." },
  { pack:"Year 2", track:"ACUTE", topic:"Endocrine", subtopic:"DKA", q:"DKA is characterised by:", choices:["Ketones + metabolic acidosis + dehydration","Low ketones + alkalosis","Low glucose always","High sodium always"], answerIndex:0, explanation:"DKA = hyperglycaemia, ketones, metabolic acidosis, dehydration." },
  { pack:"Year 2", track:"ACUTE", topic:"Gastrointestinal", subtopic:"Upper GI bleed", q:"Which suggests an upper GI bleed?", choices:["Coffee-ground vomit or melaena","Green sputum","Runny nose","Itchy eyes"], answerIndex:0, explanation:"Upper GI bleed often presents with melaena/coffee-ground vomit." },
  { pack:"Year 2", track:"ACUTE", topic:"Gastrointestinal", subtopic:"Vomiting risks", q:"Prolonged vomiting commonly causes:", choices:["Metabolic alkalosis + hypokalaemia","Metabolic acidosis","Hyperkalaemia","Respiratory acidosis"], answerIndex:0, explanation:"Loss of gastric acid + potassium loss → alkalosis + hypokalaemia." }
);
window.QUESTION_BANK.push(
  // ===== LTC: diabetes complications, education, thyroid =====
  { pack:"Year 2", track:"LTC", topic:"Endocrine", subtopic:"Diabetes complications", q:"Which is a key nursing priority to reduce diabetic foot complications long-term?", choices:["Avoid foot checks","Regular foot checks + footwear advice + early reporting of ulcers","Only check feet if painful","Use hot water bottles on feet"], answerIndex:1, explanation:"Routine foot care and early reporting reduce ulceration and amputation risk." },
  { pack:"Year 2", track:"LTC", topic:"Endocrine", subtopic:"Hypo prevention", q:"Best advice to reduce hypoglycaemia risk with insulin is:", choices:["Skip meals","Match insulin to food intake and monitor blood glucose regularly","Double doses when stressed","Avoid checking BG"], answerIndex:1, explanation:"Hypo prevention: monitoring, meal planning, dose timing, and education." },
  { pack:"Year 2", track:"LTC", topic:"Endocrine", subtopic:"Thyroid", q:"Which pattern best fits hypothyroidism?", choices:["Heat intolerance + tachycardia","Cold intolerance + fatigue + weight gain","Fruity breath","Wheeze only"], answerIndex:1, explanation:"Hypothyroidism often causes cold intolerance, fatigue, weight gain, bradycardia." },

  // ===== ACUTE: DKA/HHS, dehydration, GI obstruction =====
  { pack:"Year 2", track:"ACUTE", topic:"Endocrine", subtopic:"HHS recognition", q:"Which feature is more typical of HHS than DKA?", choices:["Marked ketones and acidosis","Very high glucose with severe dehydration and minimal ketones","Always low glucose","Always respiratory alkalosis"], answerIndex:1, explanation:"HHS: very high glucose, dehydration, hyperosmolality; ketones often minimal." },
  { pack:"Year 2", track:"ACUTE", topic:"Endocrine", subtopic:"DKA signs", q:"Which symptom supports DKA?", choices:["Kussmaul breathing and abdominal pain","Itchy eyes only","Ankle oedema only","Nasal congestion"], answerIndex:0, explanation:"DKA can cause metabolic acidosis → Kussmaul breathing; abdominal pain common." },
  { pack:"Year 2", track:"ACUTE", topic:"Gastrointestinal", subtopic:"Bowel obstruction", q:"Which set is most suggestive of bowel obstruction?", choices:["Normal bowel motions","Colicky pain + vomiting + abdominal distension + no flatus","Cough + wheeze","Headache only"], answerIndex:1, explanation:"Obstruction: pain, vomiting, distension, reduced/absent stool/flatus." },
  { pack:"Year 2", track:"ACUTE", topic:"Gastrointestinal", subtopic:"Aspiration risk", q:"Patient coughs during oral intake. Best immediate action?", choices:["Encourage faster eating","Stop feeding, sit upright, assess swallow and escalate for review","Give thin fluids","Lie flat"], answerIndex:1, explanation:"Coughing during intake suggests aspiration risk—stop and escalate for swallow assessment." }
);
window.QUESTION_BANK.push(
  // ===== LTC: diabetes, steroids, thyroid =====
  { pack:"Year 2", track:"LTC", topic:"Endocrine", subtopic:"HbA1c meaning", q:"HbA1c mainly reflects:", choices:["Blood glucose over ~2–3 months","Blood pressure only","Kidney function","Lung function"], answerIndex:0, explanation:"HbA1c reflects average glycaemia over the lifespan of red cells (~2–3 months)." },
  { pack:"Year 2", track:"LTC", topic:"Endocrine", subtopic:"Hypo treatment", q:"Conscious patient with hypoglycaemia—best immediate treatment?", choices:["Long-acting insulin","Fast-acting glucose (e.g., glucose tablets/juice) then longer-acting carbs","No food","High fat meal only"], answerIndex:1, explanation:"Treat with fast-acting glucose then follow with longer-acting carbs to prevent recurrence." },
  { pack:"Year 2", track:"LTC", topic:"Endocrine", subtopic:"Sick day rules", q:"Diabetes sick day guidance commonly includes:", choices:["Stop all insulin always","More frequent glucose monitoring and hydration; seek help if unable to keep fluids down","Avoid checking BG","Only sleep"], answerIndex:1, explanation:"Monitor BG more often; risk of DKA/HHS increases when unwell." },
  { pack:"Year 2", track:"LTC", topic:"Endocrine", subtopic:"Steroids & BG", q:"A patient started on steroids. What nursing monitoring is important long term?", choices:["Only temperature","Blood glucose monitoring for hyperglycaemia","Only oxygen sats","Only hearing test"], answerIndex:1, explanation:"Steroids can raise glucose; monitor and educate." },
  { pack:"Year 2", track:"LTC", topic:"Gastrointestinal", subtopic:"GERD lifestyle", q:"Which lifestyle change can help GERD symptoms?", choices:["Large meals late at night","Smaller meals and avoiding triggers; elevate head of bed","More spicy food","Lie flat after meals"], answerIndex:1, explanation:"Lifestyle can reduce reflux symptoms." },

  // ===== ACUTE: DKA/HHS, dehydration, GI bleed, obstruction =====
  { pack:"Year 2", track:"ACUTE", topic:"Endocrine", subtopic:"Hypoglycaemia safety", q:"If a patient is unconscious with suspected hypoglycaemia, best action?", choices:["Give oral juice","Escalate urgently and follow hypoglycaemia emergency protocol","Wait 30 minutes","Give insulin"], answerIndex:1, explanation:"Unconscious = airway risk; follow emergency protocol and escalate." },
  { pack:"Year 2", track:"ACUTE", topic:"Endocrine", subtopic:"DKA vs HHS", q:"Which is more typical of DKA than HHS?", choices:["Minimal ketones","Marked ketones and acidosis","Normal respiration always","Low glucose"], answerIndex:1, explanation:"DKA has ketosis and acidosis; HHS has minimal ketones." },
  { pack:"Year 2", track:"ACUTE", topic:"Gastrointestinal", subtopic:"GI bleed shock", q:"Which observation suggests significant GI bleed impact?", choices:["Normal BP and HR","Tachycardia and postural drop in BP","Warm hands only","Increased appetite"], answerIndex:1, explanation:"Tachycardia and postural hypotension suggest volume loss." },
  { pack:"Year 2", track:"ACUTE", topic:"Gastrointestinal", subtopic:"Pancreatitis clue", q:"Which is a common feature of acute pancreatitis?", choices:["Severe epigastric pain radiating to the back","Itchy ankles","Dry cough only","Unilateral calf swelling"], answerIndex:0, explanation:"Pancreatitis often causes severe epigastric pain radiating to back with nausea/vomiting." },
  { pack:"Year 2", track:"ACUTE", topic:"Gastrointestinal", subtopic:"Dehydration", q:"Which is a key risk of severe diarrhoea?", choices:["Fluid/electrolyte imbalance","Hyperoxygenation","Improved kidney function","Reduced thirst"], answerIndex:0, explanation:"Diarrhoea can cause dehydration and electrolyte imbalance." }
);
